version: '3.8'

services:
  administrativo-service:
    build:
      context: ./
      dockerfile: ./Administrativo/Dockerfile
    image: administrativo:latest
    ports:
      - "8081:8080"  # Puerto host único
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend
    command: >
      /bin/bash -c "
      while ! nc -z sqlserver 1433; do
        echo 'Esperando SQL Server...';
        sleep 3;
      done;
      dotnet ef database update -p DAL -s Administrativo &&
      dotnet Administrativo.dll"

  autenticacion-service:
    build:
      context: ./
      dockerfile: ./Autenticacion/Dockerfile
    image: autenticacion:latest
    ports:
      - "8082:8080"  # Puerto host único
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET=mySuperSecretKey12345!mySuperSecretKey12345!
      - JWT_ISSUER=http://localhost:8082
      - JWT_AUDIENCE=http://localhost:8082
    depends_on:
      - sqlserver
    networks:
      - backend

  gestion-citas-service:
    build:
      context: ./
      dockerfile: ./GestionCitas/Dockerfile
    image: gestioncitas:latest
    ports:
      - "8083:8080"  # Puerto host único
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend

  historias-clinicas-service:
    build:
      context: ./
      dockerfile: ./HistoriasClinicas/Dockerfile
    image: historiasclinicas:latest
    ports:
      - "8084:8080"  # Puerto host único
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend

  portal-paciente-service:
    build:
      context: ./
      dockerfile: ./PortalPaciente/Dockerfile
    image: portalpaciente:latest
    ports:
      - "8085:8080"  # Puerto host único
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend

  gestion-usuarios-service:
    build:
      context: ./
      dockerfile: ./GestionUsuarios/Dockerfile
    image: gestionusuarios:latest
    ports:
      - "8086:8080"  # Puerto host único
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - administrativo-service
      - autenticacion-service
      - gestion-citas-service
      - historias-clinicas-service
      - portal-paciente-service
      - gestion-usuarios-service
    networks:
      - backend

  frontend:
    build:
      context: ../Front.Net
      dockerfile: Dockerfile
    image: frontend:latest
    networks:
      - backend
    ports:
      - "3000:3000"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=P45w0rd.N3T
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management  
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=dotnetlab
      - RABBITMQ_DEFAULT_PASS=P455w0rd_net
    networks:
      - backend 
  

networks:
  backend:
    name: proyecto_net_backend

volumes:
  sql_data: {}
