
services:
  administrativo-service:
    build:
      context: ./
      dockerfile: ./Administrativo/Dockerfile
    image: administrativo:latest
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend

  autenticacion-service:
    build:
      context: ./
      dockerfile: ./Autenticacion/Dockerfile
    image: autenticacion:latest
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET=mySuperSecretKey12345!
      - JWT_ISSUER=http://localhost:8082
      - JWT_AUDIENCE=http://localhost:8082
    depends_on:
      - sqlserver
    networks:
      - backend

  gestion-citas-service:
    build:
      context: ./
      dockerfile: ./GestionCitas/Dockerfile
    image: gestioncitas:latest
    ports:
      - "8083:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend

  historias-clinicas-service:
    build:
      context: ./
      dockerfile: ./HistoriasClinicas/Dockerfile
    image: historiasclinicas:latest
    ports:
      - "8084:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend

  portal-paciente-service:
    build:
      context: ./
      dockerfile: ./PortalPaciente/Dockerfile
    image: portalpaciente:latest
    ports:
      - "8085:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend

  gestion-usuarios-service:
    build:
      context: ./
      dockerfile: ./GestionUsuarios/Dockerfile
    image: gestionusuarios:latest
    ports:
      - "8086:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=P45w0rd.N3T
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend
  
  rabbitmq:
    image: rabbitmq:3-management  
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Puerto por defecto para RabbitMQ
      - "15672:15672"   # Puerto para la interfaz de gestion
    environment:
      - RABBITMQ_DEFAULT_USER=dotnetlab
      - RABBITMQ_DEFAULT_PASS=P455w0rd_net
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  sql_data: {}